### ISSUE TITLE
Crash due to NSInvalidArgumentException during Memfault API outage

### ISSUE THREAD

**Issue by bgomberg** [memfault/memfault-ios-cloud#3]
While [the API was throwing errors yesterday](https://status.memfault.com/incidents/khyqp32pc5gl), anybody running our app hit the following crash from the Memfault SDK:

<img width="1098" alt="image" src="https://github.com/user-attachments/assets/be858b22-8666-42e6-ba69-f3464352e1fc">

My Objective-C knowledge is a bit lacking to send over a PR for a fix here, but it would be great if this code could be a bit more forgiving of potentially-invalid response data from the API.

**Comment by martijnthe** [comment]
Hi @bgomberg 👋, thanks for you bug report.
We've fixed the issue and released a new version, 3.0.0, see [CHANGELOG](https://github.com/memfault/memfault-cloud-ios/blob/master/CHANGELOG.md#v300) for details.
